### ISSUE TITLE
Add GPL license

### ISSUE THREAD

**Issue by hakusaro** [Grandpa-G/ExtraRestAdmin#1]
Per the [pull request here](https://github.com/Grandpa-G/RemoteAdminConsole/pull/1) I think your intention was to open source and make this plugin freely available. If you wish to do that and allow anyone to modify and redistribute it, you need some form of open source license on this repository (which is not free software). I suggest [version three of the GPL](http://choosealicense.com/licenses/gpl-3.0/), but that's up to you to [choose](http://choosealicense.com/).

**Comment by hakusaro** [comment]
There are subsequent other things to think about [with no license](http://choosealicense.com/no-license/) which I believe(d) when I sent the pull request to your other repo, removing the OSS license.

**Comment by Grandpa-G** [comment]
I have added a GNU license. Also, the wording will be changed to try to clarify that there is no intent that any proprietary software is being offered. Other than asserting a copyright, the intention is to have no other use restrictions, though I would like to not have people make money from my work.

**Comment by hakusaro** [comment]
@Grandpa-G that makes sense, then, but you should really read what GPL v2 entitles its users to -- it does conflict with the statement you have in the repo, which is the real issue. You don't need to have a copyright statement at all, technically, because the GPL implies that. However, the GPL also implies commercial use as long as source code is distributed with the modifications and the package. This is the reason why, again, profit is a very broad term.

**Comment by Grandpa-G** [comment]
I took out any reference to copyright, let the license do the work. There should be no restrictions now except as stated in license.
